/// Simple app-level translations for English and Arabic.
/// This avoids the heavy flutter_localizations setup for a lean bilingual app.
class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    // ── General ──
    'app_name': {'en': 'EquiGuard', 'ar': 'إيكوي جارد'},
    'welcome_back': {'en': 'Welcome Back', 'ar': 'مرحباً بعودتك'},
    'sign_in': {'en': 'Sign In', 'ar': 'تسجيل الدخول'},
    'sign_up': {'en': 'Sign Up', 'ar': 'إنشاء حساب'},
    'create_account': {'en': 'Create Account', 'ar': 'إنشاء حساب جديد'},
    'email': {'en': 'Email', 'ar': 'البريد الإلكتروني'},
    'password': {'en': 'Password', 'ar': 'كلمة المرور'},
    'confirm_password': {'en': 'Confirm Password', 'ar': 'تأكيد كلمة المرور'},
    'full_name': {'en': 'Full Name', 'ar': 'الاسم الكامل'},
    'role': {'en': 'Role', 'ar': 'الدور'},
    'remember_me': {'en': 'Remember me', 'ar': 'تذكرني'},
    'forgot_password': {'en': 'Forgot Password?', 'ar': 'نسيت كلمة المرور؟'},
    'or_continue_with': {'en': 'or continue with', 'ar': 'أو المتابعة باستخدام'},
    'no_account': {'en': "Don't have an account? ", 'ar': 'ليس لديك حساب؟ '},
    'have_account': {'en': 'Already have an account? ', 'ar': 'لديك حساب بالفعل؟ '},
    'agree_terms': {'en': 'I agree to the ', 'ar': 'أوافق على '},
    'terms_conditions': {'en': 'Terms & Conditions', 'ar': 'الشروط والأحكام'},
    'and': {'en': ' and ', 'ar': ' و '},
    'privacy_policy': {'en': 'Privacy Policy', 'ar': 'سياسة الخصوصية'},
    'sign_in_subtitle': {'en': 'Sign in to continue managing your stable', 'ar': 'سجل دخولك لمتابعة إدارة الإسطبل'},
    'join_subtitle': {'en': 'Join EquiGuard to start monitoring', 'ar': 'انضم إلى إيكوي جارد لبدء المراقبة'},
    'password_reset_sent': {'en': 'Password reset link sent!', 'ar': 'تم إرسال رابط إعادة تعيين كلمة المرور!'},
    'agree_terms_error': {'en': 'Please agree to the Terms & Conditions', 'ar': 'يرجى الموافقة على الشروط والأحكام'},

    // ── Validation ──
    'enter_email': {'en': 'Please enter your email', 'ar': 'يرجى إدخال بريدك الإلكتروني'},
    'valid_email': {'en': 'Please enter a valid email', 'ar': 'يرجى إدخال بريد إلكتروني صالح'},
    'enter_password': {'en': 'Please enter your password', 'ar': 'يرجى إدخال كلمة المرور'},
    'enter_a_password': {'en': 'Please enter a password', 'ar': 'يرجى إدخال كلمة مرور'},
    'password_min_length': {'en': 'Password must be at least 6 characters', 'ar': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل'},
    'enter_name': {'en': 'Please enter your name', 'ar': 'يرجى إدخال اسمك'},
    'confirm_password_error': {'en': 'Please confirm your password', 'ar': 'يرجى تأكيد كلمة المرور'},
    'passwords_dont_match': {'en': 'Passwords do not match', 'ar': 'كلمات المرور غير متطابقة'},

    // ── Onboarding ──
    'skip': {'en': 'Skip', 'ar': 'تخطي'},
    'next': {'en': 'Next', 'ar': 'التالي'},
    'get_started': {'en': 'Get Started', 'ar': 'ابدأ الآن'},
    'onboarding_title_1': {'en': 'Real-time Health\nMonitoring', 'ar': 'مراقبة الصحة\nفي الوقت الحقيقي'},
    'onboarding_desc_1': {
      'en': 'Track your horse\'s vitals 24/7 with precision IoT sensors. Monitor heart rate, temperature, and respiration levels.',
      'ar': 'تتبع العلامات الحيوية لخيلك على مدار الساعة باستخدام أجهزة استشعار دقيقة. راقب معدل ضربات القلب ودرجة الحرارة ومستويات التنفس.'
    },
    'onboarding_title_2': {'en': 'AI-Powered\nInsights', 'ar': 'رؤى مدعومة\nبالذكاء الاصطناعي'},
    'onboarding_desc_2': {
      'en': 'Detect early signs of illness with predictive algorithms. Get smart alerts based on each horse\'s unique health profile.',
      'ar': 'اكتشف العلامات المبكرة للمرض باستخدام خوارزميات تنبؤية. احصل على تنبيهات ذكية بناءً على الملف الصحي الفريد لكل حصان.'
    },
    'onboarding_title_3': {'en': 'Stay Connected\nAnywhere', 'ar': 'ابقَ على اتصال\nفي أي مكان'},
    'onboarding_desc_3': {
      'en': 'Monitor location, activity, and stable conditions from anywhere. Real-time GPS tracking keeps you informed.',
      'ar': 'راقب الموقع والنشاط وظروف الإسطبل من أي مكان. يبقيك تتبع GPS في الوقت الحقيقي على اطلاع دائم.'
    },

    // ── Settings ──
    'settings': {'en': 'Settings', 'ar': 'الإعدادات'},
    'manage_preferences': {'en': 'Manage your preferences', 'ar': 'إدارة تفضيلاتك'},
    'preferences': {'en': 'Preferences', 'ar': 'التفضيلات'},
    'push_notifications': {'en': 'Push Notifications', 'ar': 'الإشعارات'},
    'notifications_sub': {'en': 'Alerts, reminders & health updates', 'ar': 'التنبيهات والتذكيرات والتحديثات الصحية'},
    'dark_mode': {'en': 'Dark Mode', 'ar': 'الوضع الداكن'},
    'dark_mode_sub': {'en': 'Reduce eye strain in low light', 'ar': 'تقليل إجهاد العين في الإضاءة المنخفضة'},
    'biometric_lock': {'en': 'Biometric Lock', 'ar': 'القفل البيومتري'},
    'biometric_sub': {'en': 'Fingerprint or face ID', 'ar': 'بصمة الإصبع أو التعرف على الوجه'},
    'temperature_unit': {'en': 'Temperature Unit', 'ar': 'وحدة الحرارة'},
    'language': {'en': 'Language', 'ar': 'اللغة'},
    'language_sub': {'en': 'Switch between English and Arabic', 'ar': 'التبديل بين العربية والإنجليزية'},
    'english': {'en': 'English', 'ar': 'الإنجليزية'},
    'arabic': {'en': 'Arabic', 'ar': 'العربية'},
    'farm_details': {'en': 'Farm Details', 'ar': 'تفاصيل المزرعة'},
    'farm_name': {'en': 'Farm Name', 'ar': 'اسم المزرعة'},
    'location': {'en': 'Location', 'ar': 'الموقع'},
    'horses': {'en': 'Horses', 'ar': 'الخيول'},
    'registered': {'en': 'registered', 'ar': 'مسجّل'},
    'staff_members': {'en': 'Staff Members', 'ar': 'أعضاء الفريق'},
    'active': {'en': 'active', 'ar': 'نشط'},
    'data_management': {'en': 'Data Management', 'ar': 'إدارة البيانات'},
    'export_health_data': {'en': 'Export Health Data', 'ar': 'تصدير البيانات الصحية'},
    'export_sub': {'en': 'CSV report for all horses', 'ar': 'تقرير CSV لجميع الخيول'},
    'backup_sync': {'en': 'Backup & Sync', 'ar': 'النسخ الاحتياطي والمزامنة'},
    'backup_sub': {'en': 'Last backup: 2h ago', 'ar': 'آخر نسخ احتياطي: منذ ساعتين'},
    'clear_cache': {'en': 'Clear Cache', 'ar': 'مسح ذاكرة التخزين المؤقت'},
    'clear_cache_sub': {'en': 'Free up storage space', 'ar': 'تحرير مساحة التخزين'},
    'clear_all_data': {'en': 'Clear All Data', 'ar': 'مسح جميع البيانات'},
    'clear_all_sub': {'en': 'Warning: this cannot be undone', 'ar': 'تحذير: لا يمكن التراجع عن ذلك'},
    'about': {'en': 'About', 'ar': 'حول'},
    'tagline': {'en': 'The Future of Equine Intelligence', 'ar': 'مستقبل ذكاء الخيول'},
    'support': {'en': 'Support', 'ar': 'الدعم'},
    'privacy': {'en': 'Privacy', 'ar': 'الخصوصية'},
    'terms': {'en': 'Terms', 'ar': 'الشروط'},
    'logout': {'en': 'Log Out', 'ar': 'تسجيل الخروج'},

    // ── Roles ──
    'owner': {'en': 'Owner', 'ar': 'مالك'},
    'stable_manager': {'en': 'Stable Manager', 'ar': 'مدير الإسطبل'},
    'veterinarian': {'en': 'Veterinarian', 'ar': 'طبيب بيطري'},
    'trainer': {'en': 'Trainer', 'ar': 'المدرب'},
    'caretaker': {'en': 'Caretaker', 'ar': 'العناية'},

    // ── Dashboard / Bottom Nav ──
    'home': {'en': 'Home', 'ar': 'الرئيسية'},
    'health': {'en': 'Health', 'ar': 'الصحة'},
    'map': {'en': 'Map', 'ar': 'الخريطة'},
    'alerts': {'en': 'Alerts', 'ar': 'التنبيهات'},
    'stats': {'en': 'Stats', 'ar': 'الإحصائيات'},
    'stable': {'en': 'Stable', 'ar': 'الإسطبل'},

    // ── Splash ──
    'splash_tagline': {'en': 'Smart Equine Health Monitoring', 'ar': 'مراقبة صحة الخيول الذكية'},
    'loading': {'en': 'Loading...', 'ar': 'جاري التحميل...'},

    // ── Home Tab ──
    'good_evening': {'en': 'Good evening', 'ar': 'مساء الخير'},
    'good_morning': {'en': 'Good morning', 'ar': 'صباح الخير'},
    'good_afternoon': {'en': 'Good afternoon', 'ar': 'مساء الخير'},
    'notifications': {'en': 'Notifications', 'ar': 'الإشعارات'},
    'clear_all': {'en': 'Clear All', 'ar': 'مسح الكل'},
    'partly_cloudy': {'en': 'Partly Cloudy', 'ar': 'غائم جزئياً'},
    'humidity': {'en': 'Humidity', 'ar': 'الرطوبة'},
    'wind': {'en': 'Wind', 'ar': 'الرياح'},
    'uv_index': {'en': 'UV Index', 'ar': 'مؤشر الأشعة'},
    'heat_stress': {'en': 'Heat Stress', 'ar': 'الإجهاد الحراري'},
    'total': {'en': 'Total', 'ar': 'الإجمالي'},
    'avg_hr': {'en': 'Avg HR', 'ar': 'متوسط ن.ق'},
    'tasks': {'en': 'Tasks', 'ar': 'المهام'},
    'wellness_dashboard': {'en': 'Wellness\nDashboard', 'ar': 'لوحة\nالصحة'},
    'monitoring_management': {'en': 'Monitoring\nManagement', 'ar': 'إدارة\nالمراقبة'},
    'search_horses': {'en': 'Search horses by name or breed...', 'ar': 'ابحث عن الخيول بالاسم أو السلالة...'},
    'all': {'en': 'All', 'ar': 'الكل'},
    'stable_status': {'en': 'Stable', 'ar': 'مستقر'},
    'warning': {'en': 'Warning', 'ar': 'تحذير'},
    'critical': {'en': 'Critical', 'ar': 'حرج'},
    'healthy': {'en': 'Healthy', 'ar': 'سليم'},
    'reset': {'en': 'Reset', 'ar': 'إعادة تعيين'},
    'no_horses_found': {'en': 'No horses found', 'ar': 'لم يتم العثور على خيول'},
    'yrs': {'en': 'yrs', 'ar': 'سنة'},

    // ── Notifications ──
    'notif_heart_elevated': {'en': 'Thunder 5 — Heart rate elevated (72 bpm)', 'ar': 'ثاندر 5 — معدل ضربات القلب مرتفع (72 نبضة/د)'},
    'notif_hydration': {'en': 'Hydration alert: Stall 14 water level low', 'ar': 'تنبيه ترطيب: مستوى الماء منخفض في الحظيرة 14'},
    'notif_farrier': {'en': 'Farrier visit scheduled for tomorrow', 'ar': 'زيارة البيطار مجدولة غداً'},
    'notif_feed_done': {'en': 'Morning feed completed for all stalls', 'ar': 'تم إكمال التغذية الصباحية لجميع الحظائر'},
    'notif_heat': {'en': 'Heat stress warning: Index above 140', 'ar': 'تحذير إجهاد حراري: المؤشر فوق 140'},
    'notif_vaccine': {'en': 'Vaccination due: Spirit 3, Luna 7', 'ar': 'موعد التطعيم: سبيريت 3، لونا 7'},
    'notif_new_horse': {'en': 'New horse Apollo 12 registered', 'ar': 'تم تسجيل حصان جديد أبولو 12'},
    'time_5m': {'en': '5m ago', 'ar': 'منذ 5 دقائق'},
    'time_15m': {'en': '15m ago', 'ar': 'منذ 15 دقيقة'},
    'time_1h': {'en': '1h ago', 'ar': 'منذ ساعة'},
    'time_3h': {'en': '3h ago', 'ar': 'منذ 3 ساعات'},
    'time_4h': {'en': '4h ago', 'ar': 'منذ 4 ساعات'},
    'time_6h': {'en': '6h ago', 'ar': 'منذ 6 ساعات'},
    'time_8h': {'en': '8h ago', 'ar': 'منذ 8 ساعات'},
    'time_1d': {'en': '1d ago', 'ar': 'منذ يوم'},
    'time_2h': {'en': '2h ago', 'ar': 'منذ ساعتين'},

    // ── Stats Tab ──
    'statistics': {'en': 'Statistics', 'ar': 'الإحصائيات'},
    'health_overview': {'en': 'Health overview of your herd', 'ar': 'نظرة عامة على صحة قطيعك'},
    'alert': {'en': 'Alert', 'ar': 'تنبيه'},
    'health_distribution': {'en': 'Health Distribution', 'ar': 'توزيع الحالة الصحية'},
    'temp_trends': {'en': 'Temperature Trends (24h)', 'ar': 'اتجاهات الحرارة (24 ساعة)'},
    'weekly_avg_hr': {'en': 'Weekly Avg Heart Rate', 'ar': 'متوسط معدل ن.القلب الأسبوعي'},
    'recent_activity': {'en': 'Recent Activity', 'ar': 'النشاط الأخير'},
    'monthly_summary': {'en': 'Monthly Summary', 'ar': 'الملخص الشهري'},
    'vet_visits': {'en': 'Vet Visits', 'ar': 'زيارات البيطري'},
    'feed_cost': {'en': 'Feed Cost', 'ar': 'تكلفة العلف'},
    'health_checks': {'en': 'Health Checks', 'ar': 'الفحوصات الصحية'},
    'wellness_statistics': {'en': 'Wellness Statistics', 'ar': 'إحصائيات الصحة'},
    'overall_health': {'en': 'Overall Health Status', 'ar': 'الحالة الصحية العامة'},
    'vital_trends': {'en': 'Vital Trends (Avg)', 'ar': 'اتجاهات المؤشرات الحيوية (المتوسط)'},

    // ── Stats Activity Items ──
    'act_health_check': {'en': 'Health check completed', 'ar': 'تم إكمال الفحص الصحي'},
    'act_health_check_sub': {'en': 'Thunder 5 — All vitals normal', 'ar': 'ثاندر 5 — جميع المؤشرات طبيعية'},
    'act_alert_resolved': {'en': 'Alert resolved', 'ar': 'تم حل التنبيه'},
    'act_alert_sub': {'en': 'Spirit 3 — Heart rate normalized', 'ar': 'سبيريت 3 — معدل القلب طبيعي'},
    'act_vet_scheduled': {'en': 'Vet visit scheduled', 'ar': 'تم جدولة زيارة البيطري'},
    'act_vet_sub': {'en': 'Luna 7 — Annual vaccination', 'ar': 'لونا 7 — التطعيم السنوي'},
    'act_feeding': {'en': 'Feeding completed', 'ar': 'تم إكمال التغذية'},
    'act_feeding_sub': {'en': 'All stalls — Morning hay & grains', 'ar': 'جميع الحظائر — تبن ومكملات صباحية'},
    'act_new_horse': {'en': 'New horse added', 'ar': 'تم إضافة حصان جديد'},
    'act_new_horse_sub': {'en': 'Apollo 12 — Arabian, 5 yrs', 'ar': 'أبولو 12 — عربي، 5 سنوات'},

    // ── Days of week ──
    'mon': {'en': 'Mon', 'ar': 'إثنين'},
    'tue': {'en': 'Tue', 'ar': 'ثلاثاء'},
    'wed': {'en': 'Wed', 'ar': 'أربعاء'},
    'thu': {'en': 'Thu', 'ar': 'خميس'},
    'fri': {'en': 'Fri', 'ar': 'جمعة'},
    'sat': {'en': 'Sat', 'ar': 'سبت'},
    'sun': {'en': 'Sun', 'ar': 'أحد'},
    'day_m': {'en': 'M', 'ar': 'إ'},
    'day_t': {'en': 'T', 'ar': 'ث'},
    'day_w': {'en': 'W', 'ar': 'أ'},
    'day_th': {'en': 'T', 'ar': 'خ'},
    'day_f': {'en': 'F', 'ar': 'ج'},
    'day_s': {'en': 'S', 'ar': 'س'},
    'day_su': {'en': 'S', 'ar': 'أح'},

    // ── Horse Details ──
    'horse_details': {'en': 'Horse Details', 'ar': 'تفاصيل الحصان'},
    'overview': {'en': 'Overview', 'ar': 'نظرة عامة'},
    'vitals': {'en': 'Vitals', 'ar': 'المؤشرات الحيوية'},
    'history': {'en': 'History', 'ar': 'السجل'},
    'breed': {'en': 'Breed', 'ar': 'السلالة'},
    'age': {'en': 'Age', 'ar': 'العمر'},
    'weight': {'en': 'Weight', 'ar': 'الوزن'},
    'stall': {'en': 'Stall', 'ar': 'الحظيرة'},
    'heart_rate': {'en': 'Heart Rate', 'ar': 'معدل ضربات القلب'},
    'temperature': {'en': 'Temperature', 'ar': 'درجة الحرارة'},
    'respiration': {'en': 'Respiration', 'ar': 'التنفس'},
    'bpm': {'en': 'bpm', 'ar': 'نبضة/د'},
    'breaths_min': {'en': 'breaths/min', 'ar': 'تنفس/د'},
    'edit': {'en': 'Edit', 'ar': 'تعديل'},
    'delete': {'en': 'Delete', 'ar': 'حذف'},
    'confirm_delete': {'en': 'Are you sure you want to delete this horse?', 'ar': 'هل أنت متأكد من حذف هذا الحصان؟'},
    'yes': {'en': 'Yes', 'ar': 'نعم'},
    'no': {'en': 'No', 'ar': 'لا'},
    'cancel': {'en': 'Cancel', 'ar': 'إلغاء'},

    // ── Add/Edit Horse ──
    'add_horse': {'en': 'Add Horse', 'ar': 'إضافة حصان'},
    'edit_horse': {'en': 'Edit Horse', 'ar': 'تعديل الحصان'},
    'horse_name': {'en': 'Horse Name', 'ar': 'اسم الحصان'},
    'save': {'en': 'Save', 'ar': 'حفظ'},
    'save_changes': {'en': 'Save Changes', 'ar': 'حفظ التغييرات'},
    'horse_info': {'en': 'Horse Information', 'ar': 'معلومات الحصان'},
    'enter_horse_name': {'en': 'Enter horse name', 'ar': 'أدخل اسم الحصان'},
    'select_breed': {'en': 'Select breed', 'ar': 'اختر السلالة'},
    'enter_age': {'en': 'Enter age', 'ar': 'أدخل العمر'},
    'enter_weight': {'en': 'Enter weight (kg)', 'ar': 'أدخل الوزن (كجم)'},
    'select_status': {'en': 'Select status', 'ar': 'اختر الحالة'},
    'horse_added': {'en': 'Horse added successfully!', 'ar': 'تمت إضافة الحصان بنجاح!'},
    'horse_updated': {'en': 'Horse updated successfully!', 'ar': 'تم تحديث بيانات الحصان بنجاح!'},

    // ── Stable Management ──
    'stable_management': {'en': 'Stable Management', 'ar': 'إدارة الإسطبل'},
    'facilities': {'en': 'Facilities', 'ar': 'المرافق'},
    'staff': {'en': 'Staff', 'ar': 'الموظفون'},
    'schedule': {'en': 'Schedule', 'ar': 'الجدول'},
    'inventory': {'en': 'Inventory', 'ar': 'المخزون'},
    'stalls': {'en': 'Stalls', 'ar': 'الحظائر'},
    'occupied': {'en': 'Occupied', 'ar': 'مشغول'},
    'available': {'en': 'Available', 'ar': 'متاح'},
    'maintenance': {'en': 'Maintenance', 'ar': 'صيانة'},

    // ── Feeding ──
    'feeding_log': {'en': 'Feeding Log', 'ar': 'سجل التغذية'},
    'add_feeding': {'en': 'Add Feeding', 'ar': 'إضافة تغذية'},
    'feed_type': {'en': 'Feed Type', 'ar': 'نوع العلف'},
    'quantity': {'en': 'Quantity', 'ar': 'الكمية'},
    'hay': {'en': 'Hay', 'ar': 'تبن'},
    'grains': {'en': 'Grains', 'ar': 'حبوب'},
    'supplements': {'en': 'Supplements', 'ar': 'مكملات'},
    'morning': {'en': 'Morning', 'ar': 'صباحي'},
    'afternoon_feed': {'en': 'Afternoon', 'ar': 'ظهري'},
    'evening': {'en': 'Evening', 'ar': 'مسائي'},
    'fed_by': {'en': 'Fed by', 'ar': 'تم التغذية بواسطة'},

    // ── Vet Records ──
    'vet_records': {'en': 'Vet Records', 'ar': 'السجلات البيطرية'},
    'add_record': {'en': 'Add Record', 'ar': 'إضافة سجل'},
    'vaccination': {'en': 'Vaccination', 'ar': 'تطعيم'},
    'checkup': {'en': 'Checkup', 'ar': 'فحص'},
    'treatment': {'en': 'Treatment', 'ar': 'علاج'},
    'surgery': {'en': 'Surgery', 'ar': 'جراحة'},
    'diagnosis': {'en': 'Diagnosis', 'ar': 'تشخيص'},
    'prescribed': {'en': 'Prescribed', 'ar': 'موصوف'},
    'next_visit': {'en': 'Next Visit', 'ar': 'الزيارة القادمة'},
    'vet_name': {'en': 'Vet Name', 'ar': 'اسم البيطري'},
    'notes': {'en': 'Notes', 'ar': 'ملاحظات'},

    // ── Facility Map ──
    'facility_map': {'en': 'Facility Map', 'ar': 'خريطة المرافق'},
    'paddock': {'en': 'Paddock', 'ar': 'حظيرة'},
    'arena': {'en': 'Arena', 'ar': 'حلبة'},
    'barn': {'en': 'Barn', 'ar': 'حظيرة'},
    'office': {'en': 'Office', 'ar': 'مكتب'},
    'storage': {'en': 'Storage', 'ar': 'مخزن'},

    // ── Staff ──
    'staff_screen': {'en': 'Staff', 'ar': 'الموظفون'},
    'add_staff': {'en': 'Add Staff', 'ar': 'إضافة موظف'},
    'on_duty': {'en': 'On Duty', 'ar': 'في الخدمة'},
    'off_duty': {'en': 'Off Duty', 'ar': 'خارج الخدمة'},
    'contact': {'en': 'Contact', 'ar': 'اتصال'},

    // ── Task Board ──
    'task_board': {'en': 'Task Board', 'ar': 'لوحة المهام'},
    'to_do': {'en': 'To Do', 'ar': 'للتنفيذ'},
    'in_progress': {'en': 'In Progress', 'ar': 'قيد التنفيذ'},
    'done': {'en': 'Done', 'ar': 'مكتمل'},
    'add_task': {'en': 'Add Task', 'ar': 'إضافة مهمة'},
    'priority': {'en': 'Priority', 'ar': 'الأولوية'},
    'high': {'en': 'High', 'ar': 'عالية'},
    'medium': {'en': 'Medium', 'ar': 'متوسطة'},
    'low': {'en': 'Low', 'ar': 'منخفضة'},
    'assigned_to': {'en': 'Assigned to', 'ar': 'مسند إلى'},
    'due_date': {'en': 'Due Date', 'ar': 'تاريخ الاستحقاق'},

    // ── QR / AR ──
    'qr_scan': {'en': 'QR Scan', 'ar': 'مسح QR'},
    'ar_scan': {'en': 'AR Scan', 'ar': 'مسح AR'},
    'scan_horse_tag': {'en': 'Scan horse tag', 'ar': 'امسح علامة الحصان'},
    'tap_to_scan': {'en': 'Tap to scan', 'ar': 'اضغط للمسح'},

    // ── Horse Comparison ──
    'horse_comparison': {'en': 'Horse Comparison', 'ar': 'مقارنة الخيول'},
    'compare': {'en': 'Compare', 'ar': 'مقارنة'},
    'select_horses': {'en': 'Select horses to compare', 'ar': 'اختر خيولاً للمقارنة'},

    // ── Stable Management (extra) ──
    'daily_operations': {'en': 'Daily Operations', 'ar': 'العمليات اليومية'},
    'daily_ops_subtitle': {'en': 'Daily operations & health tasks', 'ar': 'العمليات اليومية ومهام الصحة'},
    'todays_progress': {'en': "Today's Progress", 'ar': 'تقدم اليوم'},
    'tasks_completed': {'en': 'tasks completed', 'ar': 'مهام مكتملة'},
    'ops': {'en': 'Ops', 'ar': 'عمليات'},
    'health_maintenance': {'en': 'Health Maintenance', 'ar': 'الصيانة الصحية'},
    'heat_stress_index': {'en': 'Heat Stress Index', 'ar': 'مؤشر الإجهاد الحراري'},
    'moderate_risk': {'en': 'Moderate risk • Ensure shade and water access', 'ar': 'خطر متوسط • تأكد من توفر الظل والماء'},
    'caution': {'en': 'CAUTION', 'ar': 'تنبيه'},
    'morning_feed': {'en': 'Morning Feed', 'ar': 'التغذية الصباحية'},
    'water_trough_check': {'en': 'Water Trough Check', 'ar': 'فحص حوض الماء'},
    'stall_mucking': {'en': 'Stall Mucking', 'ar': 'تنظيف الحظيرة'},
    'turnout_paddock': {'en': 'Turn-out / Paddock', 'ar': 'الخروج / المرعى'},
    'afternoon_feed_task': {'en': 'Afternoon Feed', 'ar': 'التغذية الظهرية'},
    'equipment_check': {'en': 'Equipment Check', 'ar': 'فحص المعدات'},
    'evening_feed': {'en': 'Evening Feed', 'ar': 'التغذية المسائية'},
    'night_check': {'en': 'Night Check', 'ar': 'فحص ليلي'},
    'hoof_inspection': {'en': 'Hoof Inspection', 'ar': 'فحص الحوافر'},
    'grooming': {'en': 'Grooming (All Horses)', 'ar': 'تنظيف (كل الخيول)'},
    'vitals_monitoring': {'en': 'Vitals Monitoring', 'ar': 'مراقبة المؤشرات'},
    'medication_admin': {'en': 'Medication Admin', 'ar': 'إعطاء الدواء'},
    'wound_dressing': {'en': 'Wound Dressing', 'ar': 'تضميد الجروح'},

    // ── Feeding Log (extra) ──
    'daily_feeding_progress': {'en': 'Daily Feeding Progress', 'ar': 'تقدم التغذية اليومية'},
    'completed': {'en': 'completed', 'ar': 'مكتملة'},
    'morning_hay': {'en': 'Morning Hay', 'ar': 'تبن صباحي'},
    'grain_mix': {'en': 'Grain Mix', 'ar': 'خليط الحبوب'},
    'midday_hay': {'en': 'Midday Hay', 'ar': 'تبن الظهيرة'},
    'water_check': {'en': 'Water Check', 'ar': 'فحص الماء'},
    'evening_grain': {'en': 'Evening Grain', 'ar': 'حبوب مسائية'},
    'evening_hay': {'en': 'Evening Hay', 'ar': 'تبن مسائي'},
    'salt_block': {'en': 'Salt Block', 'ar': 'قالب ملح'},

    // ── Vet Records (extra) ──
    'veterinary_records': {'en': 'Veterinary Records', 'ar': 'السجلات البيطرية'},
    'upcoming_appointments': {'en': 'Upcoming Appointments', 'ar': 'المواعيد القادمة'},
    'treatment_history': {'en': 'Treatment History', 'ar': 'تاريخ العلاج'},
    'new_record': {'en': 'New Record', 'ar': 'سجل جديد'},
    'follow_up': {'en': 'Follow-up', 'ar': 'متابعة'},
    'close': {'en': 'Close', 'ar': 'إغلاق'},

    // ── Facility Map (extra) ──
    'barn_layout': {'en': 'Barn Layout', 'ar': 'تخطيط الحظيرة'},
    'tap_stall_details': {'en': 'Tap a stall for details', 'ar': 'اضغط على حظيرة للتفاصيل'},
    'outdoor_zones': {'en': 'Outdoor Zones', 'ar': 'المناطق الخارجية'},
    'paddocks': {'en': 'Paddocks', 'ar': 'المراعي'},
    'empty': {'en': 'Empty', 'ar': 'فارغ'},
    'horse_label': {'en': 'Horse', 'ar': 'الحصان'},
    'temp_label': {'en': 'Temp', 'ar': 'الحرارة'},
    'water_label': {'en': 'Water', 'ar': 'الماء'},
    'maint': {'en': 'Maint.', 'ar': 'صيانة'},

    // ── Staff (extra) ──
    'team': {'en': 'Team', 'ar': 'الفريق'},
    'leaderboard': {'en': 'Leaderboard', 'ar': 'لوحة المتصدرين'},
    'on_shift': {'en': 'On Shift', 'ar': 'في المناوبة'},
    'off_shift': {'en': 'Off Shift', 'ar': 'خارج المناوبة'},
    'off_today': {'en': 'Off Today', 'ar': 'إجازة اليوم'},
    'upcoming': {'en': 'Upcoming', 'ar': 'قادم'},

    // ── Task Board (extra) ──
    'create_new_task': {'en': 'Create new task', 'ar': 'إنشاء مهمة جديدة'},
    'back': {'en': '← Back', 'ar': '→ رجوع'},
    'next_task': {'en': 'Next →', 'ar': '← التالي'},

    // ── QR Scan (extra) ──
    'qr_scanner': {'en': 'QR Scanner', 'ar': 'ماسح QR'},
    'point_at_qr': {'en': 'Point at a stall QR code', 'ar': 'وجّه نحو رمز QR للحظيرة'},
    'scan_another': {'en': 'Scan Another', 'ar': 'مسح آخر'},

    // ── AR Scan (extra) ──
    'ar_linked': {'en': 'AR LINKED', 'ar': 'AR مرتبط'},
    'ar_view_active': {'en': 'AR VIEW ACTIVE', 'ar': 'عرض AR نشط'},
    'scanning': {'en': 'Scanning...', 'ar': 'جاري المسح...'},
    'hold_steady': {'en': 'Hold steady • Point at horse', 'ar': 'ثبّت الجهاز • وجّهه نحو الحصان'},
    'horse_detected': {'en': 'Horse Detected', 'ar': 'تم كشف الحصان'},
    'view_full_report': {'en': 'View Full Report', 'ar': 'عرض التقرير الكامل'},
    'head': {'en': 'Head', 'ar': 'الرأس'},
    'chest': {'en': 'Chest', 'ar': 'الصدر'},
    'legs': {'en': 'Legs', 'ar': 'الأرجل'},
    'body': {'en': 'Body', 'ar': 'الجسم'},
    'normal': {'en': 'Normal', 'ar': 'طبيعي'},
    'gait_ok': {'en': 'Gait OK', 'ar': 'المشية جيدة'},

    // ── Horse Comparison (extra) ──
    'compare_horses': {'en': 'Compare Horses', 'ar': 'مقارنة الخيول'},
    'select_horse': {'en': 'Select Horse', 'ar': 'اختر حصاناً'},
    'select_two_horses': {'en': 'Select two horses to compare', 'ar': 'اختر حصانين للمقارنة'},
    'summary': {'en': 'Summary', 'ar': 'ملخص'},
    'vacc': {'en': 'Vacc.', 'ar': 'تطعيم'},
    'gait': {'en': 'Gait', 'ar': 'المشية'},
    'status': {'en': 'Status', 'ar': 'الحالة'},
    'hydration_label': {'en': 'Hydration', 'ar': 'الترطيب'},
    'stress_label': {'en': 'Stress', 'ar': 'التوتر'},
    'name': {'en': 'Name', 'ar': 'الاسم'},
    'health_status': {'en': 'Health Status', 'ar': 'الحالة الصحية'},
    'save_horse': {'en': 'Save Horse', 'ar': 'حفظ الحصان'},
  };

  /// Get a translated string. Falls back to English if key or language is missing.
  static String get(String key, String languageCode) {
    final entry = _strings[key];
    if (entry == null) return key;
    return entry[languageCode] ?? entry['en'] ?? key;
  }
}
